###Get timezones of user
GET http://localhost:8080/rest/timezones/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdtU2ZzN1RHUkR0REx0NWhwOWZvaSJ9.eyJpc3MiOiJodHRwczovL2Rldi0wbm40dTU5dS51cy5hdXRoMC5jb20vIiwic3ViIjoieWdNcGdRS3lSUzd5TmhIZEVOeFpIVFUxSTVMRUJpM29AY2xpZW50cyIsImF1ZCI6ImFwaSIsImlhdCI6MTYyNzE5NjM3MSwiZXhwIjoxNjI3MjgyNzcxLCJhenAiOiJ5Z01wZ1FLeVJTN3lOaEhkRU54WkhUVTFJNUxFQmkzbyIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbXX0.YBkI7NhgwNBy1Zxpu6BKYzbpNvHQZbsNVmATNsNXnlwu37abzsK7044MJWsqV_NAiDv_vGXyY3KaR4ky8BxjaSNz1l5r7S2z9k5-Zq_FXfpVScUYW7BkK4ft_Dqq77BIjAm8sETc4Rmc78gOiyA26Ya8O2cqSlnGH4pF5uJauSn0hQmSZop1x85BOM9vpdMP1f2pn7U763PkDzkU9Fa9xdzP7TKw6SIwPv3qkeS87KdbMhjKaqW_kXrWMN2SwYxNmTusP_zx5ZkV3KoHhw1AeUXyZLXNjTWPw2gHWqy29K-A6KNCf0roUPBk4Cvk-5yoLchW4b3DxJf1orsgf6isiQ
Accept: application/json


### Add timezone to user
POST http://localhost:8080/rest/timezones/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdtU2ZzN1RHUkR0REx0NWhwOWZvaSJ9.eyJpc3MiOiJodHRwczovL2Rldi0wbm40dTU5dS51cy5hdXRoMC5jb20vIiwic3ViIjoieWdNcGdRS3lSUzd5TmhIZEVOeFpIVFUxSTVMRUJpM29AY2xpZW50cyIsImF1ZCI6ImFwaSIsImlhdCI6MTYyNzE5NjM3MSwiZXhwIjoxNjI3MjgyNzcxLCJhenAiOiJ5Z01wZ1FLeVJTN3lOaEhkRU54WkhUVTFJNUxFQmkzbyIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbXX0.YBkI7NhgwNBy1Zxpu6BKYzbpNvHQZbsNVmATNsNXnlwu37abzsK7044MJWsqV_NAiDv_vGXyY3KaR4ky8BxjaSNz1l5r7S2z9k5-Zq_FXfpVScUYW7BkK4ft_Dqq77BIjAm8sETc4Rmc78gOiyA26Ya8O2cqSlnGH4pF5uJauSn0hQmSZop1x85BOM9vpdMP1f2pn7U763PkDzkU9Fa9xdzP7TKw6SIwPv3qkeS87KdbMhjKaqW_kXrWMN2SwYxNmTusP_zx5ZkV3KoHhw1AeUXyZLXNjTWPw2gHWqy29K-A6KNCf0roUPBk4Cvk-5yoLchW4b3DxJf1orsgf6isiQ
Accept: application/json
Content-Type: application/json

{
  "timezoneName": "Italy/Rome",
  "timezoneCity": "Rome",
  "gmtDifferenceMinutes": 120
}


###Delete timezone for user
DELETE http://localhost:8080/rest/timezones/Italy%2FRome
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdtU2ZzN1RHUkR0REx0NWhwOWZvaSJ9.eyJpc3MiOiJodHRwczovL2Rldi0wbm40dTU5dS51cy5hdXRoMC5jb20vIiwic3ViIjoieWdNcGdRS3lSUzd5TmhIZEVOeFpIVFUxSTVMRUJpM29AY2xpZW50cyIsImF1ZCI6ImFwaSIsImlhdCI6MTYyNzE5NjM3MSwiZXhwIjoxNjI3MjgyNzcxLCJhenAiOiJ5Z01wZ1FLeVJTN3lOaEhkRU54WkhUVTFJNUxFQmkzbyIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbXX0.YBkI7NhgwNBy1Zxpu6BKYzbpNvHQZbsNVmATNsNXnlwu37abzsK7044MJWsqV_NAiDv_vGXyY3KaR4ky8BxjaSNz1l5r7S2z9k5-Zq_FXfpVScUYW7BkK4ft_Dqq77BIjAm8sETc4Rmc78gOiyA26Ya8O2cqSlnGH4pF5uJauSn0hQmSZop1x85BOM9vpdMP1f2pn7U763PkDzkU9Fa9xdzP7TKw6SIwPv3qkeS87KdbMhjKaqW_kXrWMN2SwYxNmTusP_zx5ZkV3KoHhw1AeUXyZLXNjTWPw2gHWqy29K-A6KNCf0roUPBk4Cvk-5yoLchW4b3DxJf1orsgf6isiQ
Accept: application/json





### Admin get timezones
GET http://localhost:8080/rest/admin/users/google-oauth2%7C113300806490854534957/timezones/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdtU2ZzN1RHUkR0REx0NWhwOWZvaSJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiQWRtaW4iXSwiaXNzIjoiaHR0cHM6Ly9kZXYtMG5uNHU1OXUudXMuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTEzMzAwODA2NDkwODU0NTM0OTU3IiwiYXVkIjpbImFwaSIsImh0dHBzOi8vZGV2LTBubjR1NTl1LnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2MjcyMzMyNTksImV4cCI6MTYyNzMxOTY1OSwiYXpwIjoicTVZOHJ3Y242VldmT1dqVUUwNUlsWnhYeHVLdkF6SXIiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOltdfQ.RzxVGrTzqnBUgNSC_OWiJ0tMzg7fHpWT8OoVEl0DM1D74fumzkvGLLfXkMtyxwMT1JAcDi9B-knbDI93oEV3SAm5qLZXhBccfqE5rjYppOKMwOOYRbHYy1awPKKxvk3Lz6dSi-HnPEZgrerGDijV2FmJbgpBwO38x4uiLcj5D6NPXANptGdNBh7CSG9n76JJH9pE0rrevt3VVyM_QCs5zACTeOcL9jbD-CnWpTYGcxZKsnnkzJKka6wKaYGInbrNhzf1Wuav4tHLbjfr3on_ePrmqn4tGIBcajzqSEl2oB31PW5VPQKc_JFPBl5tLs3EOnOH-CTwzb0fx0-GTisEoQ
Accept: application/jsons
