###Get timezones of user
GET http://localhost:8080/rest/timezones/
Authorization: Bearer
Accept: application/json


### Add timezone to user
POST http://localhost:8080/rest/timezones/
Authorization: Bearer
Accept: application/json
Content-Type: application/json

{
  "timezoneName": "Italy/Rome",
  "timezoneCity": "Rome",
  "gmtDifferenceMinutes": 120
}


###Delete timezone for user
DELETE http://localhost:8080/rest/timezones/Italy%2FRome
Authorization: Bearer
Accept: application/json


### Admin get users
GET http://localhost:8080/rest/admin/users/?search=al
Authorization: Bearer
Accept: application/jsons
